language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - REACT_APP_API_BASE_URL=http://localhost:8080
    - PACT_BROKER_URL=https://evizi.pactflow.io
    - GIT_BRANCH=${TRAVIS_BRANCH}
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  - make ci